### ISSUE TITLE
Calendar widget links to null ID reference

### ISSUE THREAD

**Issue by BenJetson** [mannrobo/mannrobo.github.io#19]
All of the links in the calendar widget link to a null ID reference (`href="#"`).
They should link to the event page. For example, "Volunteering @ Sevier" on NOV 4, 2017 should link to [this page](https://calendar.google.com/calendar/render?eid=NzYxMWg0NGIyMTJia2I2ZWhmYm5iajNqZ3MgZ3JlZW52aWxsZXNjaG9vbHMudXNfaGQ4ajdzZGNkY2w3cWhibXV0bzV0cmJwazBAZw&ctz=America/New_York&sf=true&output=xml#eventpage_6).

You can get the link you need easily from the Google Calendar Events API: 
see documentation here: https://developers.google.com/google-apps/calendar/v3/reference/events
(do a `CTRL+F` and search for `htmlLink`)
![image](https://user-images.githubusercontent.com/10427974/32256198-00303316-be84-11e7-93d3-4372c4184540.png)

**Comment by brenapp** [comment]
I just haven't added the modals yet. It'll be in the next release

**Comment by BenJetson** [comment]
Ahh. A modal dialog will look nice there, provided it creates a polished UX that doesn't break the flow of the page. 
**Be sure the model includes a link like "More Details" or something to that page** still, though. Not everything is easily digestible through the API or feasible to display on the website.
