### ISSUE TITLE
Change C team name on digital properties

### ISSUE THREAD

**Issue by brenapp** [mannrobo/mannrobo.github.io#23]
Change to "Don't forget to breath"

**Comment by brenapp** [comment]
Fixed in c78fde0ade1e2b4e8c0e8703c581fa84bf9baeec

**Comment by BenJetson** [comment]
Honestly not sure how, but you managed to get the name wrong. :stuck_out_tongue: The correct name is `Don't Forget to Breathe`. You put `Breath`.

**Comment by brenapp** [comment]
O___o

Blame my tired brain. On it!
