### ISSUE TITLE
Create a custom HTTP 404 page

### ISSUE THREAD

**Issue by BenJetson** [mannrobo/mannrobo.github.io#26]
Our site would look better with its own custom 404 page, especially since it's currently littered with broken links. Adding one is very simple.

See relevant Jekyll Documentation here:
[https://jekyllrb.com/tutorials/custom-404-page/](https://jekyllrb.com/tutorials/custom-404-page/)

**Comment by brenapp** [comment]
As far as I know, there are no broken links. If you find any, post them here
